name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pyinstaller pyautogui pydirectinput customtkinter keyboard pillow pygetwindow
    
    - name: Build exe
      run: |
        pyinstaller --onefile --add-data "image.png;." --icon=logo.ico --name "Auto Haki Observation" --noconsole sailorpiece.py
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Auto Haki Observation.exe
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
